### ISSUE TITLE
Failed to load the indent-detective package

### ISSUE THREAD

**Issue by JeremyCavanagh** [JunoLab/atom-indent-detective#7]
[Enter steps to reproduce:]

1. Start Atom
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.11.6
**Thrown From**: [indent-detective](https://github.com/JunoLab/atom-indent-detective) package 0.2.2

### Stack Trace

Failed to load the indent-detective package

```
At Cannot find module './helpers'

Error: Cannot find module './helpers'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Develop/Text Editors/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Develop/Text Editors/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Develop/Text Editors/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/julia-client/node_modules/emissary/lib/emissary.js:4:13)
    at /packages/julia-client/node_modules/emissary/lib/emissary.js:14:4)
    at /packages/julia-client/node_modules/emissary/lib/emissary.js:16:3)
    at Module.get_Module._compile (/Applications/Develop/Text Editors/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Develop/Text Editors/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Develop/Text Editors/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/julia-client/node_modules/grim/lib/grim.js:4:13)
    at /packages/julia-client/node_modules/grim/lib/grim.js:112:4)
    at /packages/julia-client/node_modules/grim/lib/grim.js:114:3)
    at Module.get_Module._compile (/Applications/Develop/Text Editors/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Develop/Text Editors/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Develop/Text Editors/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/julia-client/node_modules/space-pen/lib/space-pen.js:10:12)
    at /packages/julia-client/node_modules/space-pen/lib/space-pen.js:634:4)
    at /packages/julia-client/node_modules/space-pen/lib/space-pen.js:636:3)
    at Module.get_Module._compile (/Applications/Develop/Text Editors/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Develop/Text Editors/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
```

### Commands

```
```

### Non-Core Packages

```
atom-julia-run 1.0.5 
busy-signal 1.4.3 
Hydrogen 2.5.1 
indent-detective 0.2.2 
ink 0.9.2 
intentions 1.1.5 
julia-client 0.7.1 
language-julia 0.16.0 
latex-completions 0.3.5 
linter 2.2.0 
linter-julia 0.7.3 
linter-ui-default 1.7.1 
tool-bar 1.1.7 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment]
Can you uninstall indent-detective and restart Atom? The stacktrace indicates that this package isn't actually the problem.
